# Generated by Django 6.0.2 on 2026-02-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HairStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField(help_text='Price in Kenyan Shillings (KES)')),
                ('description', models.TextField(blank=True, help_text='Details about the service (e.g., duration, requirements)')),
                ('image', models.ImageField(blank=True, help_text='Upload a professional photo of this style', null=True, upload_to='hairstyles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hair Style',
                'verbose_name_plural': 'Hair Styles',
                'ordering': ['price'],
            },
        ),
    ]
