# Generated by Django 6.0.2 on 2026-02-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('whatsapp_clicks', models.PositiveIntegerField(default=0)),
                ('review_submissions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Site Analytics',
                'verbose_name_plural': 'Site Analytics',
            },
        ),
    ]
